[package]
name = "azure"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1"
<<<<<<< HEAD
azure_core = { version = "0.1.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
azure_identity = { version = "0.1.0", git = "https://github.com/Azure/azure-sdk-for-rust" }
azure_storage = { version = "0.1.0", git = "https://github.com/Azure/azure-sdk-for-rust", default-features = false, features = ["account", "blob"] }
=======
# TODO: The azure sdk with the newest version needs the rustc v1.70, but current version of rustc in TiKV is v1.67.
#     Therefore use the patch to update sdk to support fips 140.
azure_core = { git = "https://github.com/tikv/azure-sdk-for-rust", branch = "release-7.5-fips" }
azure_identity = { git = "https://github.com/tikv/azure-sdk-for-rust", branch = "release-7.5-fips" }
azure_security_keyvault = { git = "https://github.com/tikv/azure-sdk-for-rust", branch = "release-7.5-fips", default-features = false }
azure_storage = { git = "https://github.com/tikv/azure-sdk-for-rust", branch = "release-7.5-fips", default-features = false }
azure_storage_blobs = { git = "https://github.com/tikv/azure-sdk-for-rust", branch = "release-7.5-fips" }
>>>>>>> 1afb327c6d (cloud: update cloud sdk that supports fips 140 for cloud sdk (#16098))
base64 = "0.13"
chrono = "0.4"
cloud = { workspace = true }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
kvproto = { workspace = true }
lazy_static = "1.4.0"
oauth2 = { version = "4.0.0", default-features = false }
regex = "1"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_util = { workspace = true }
tokio = { version = "1.5", features = ["time"] }
url = "2.0"
