[package]
name = "crypto"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
openssl = { workspace = true }
openssl-sys = { workspace = true }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
